In [1]:
pip install easygui

Requirement already satisfied: easygui in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (0.98.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import easygui

In [3]:
path=easygui.fileopenbox()

In [4]:
df=pd.read_csv(path)

In [5]:
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [6]:
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [7]:
df.info()      # technical info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [8]:
df['years']=df['YearsExperience'].astype(int)  # To change the datatypes

In [11]:
df

    YearsExperience    Salary  years
0                 1   39343.0      1
1                 1   46205.0      1
2                 1   37731.0      1
3                 2   43525.0      2
4                 2   39891.0      2
5                 2   56642.0      2
6                 3   60150.0      3
7                 3   54445.0      3
8                 3   64445.0      3
9                 3   57189.0      3
10                3   63218.0      3
11                4   55794.0      4
12                4   56957.0      4
13                4   57081.0      4
14                4   61111.0      4
15                4   67938.0      4
16                5   66029.0      5
17                5   83088.0      5
18                5   81363.0      5
19                6   93940.0      6
20                6   91738.0      6
21                7   98273.0      7
22                7  101302.0      7
23                8  113812.0      8
24                8  109431.0      8
25                9  105582.0      9
26                9  116969.0      9
27                9  112635.0      9
28               10  122391.0     10
29               10  121872.0     10

In [12]:
df["YearsExperience"]=df['YearsExperience'].astype(int)   # To chnage data types
df

    YearsExperience    Salary  years
0                 1   39343.0      1
1                 1   46205.0      1
2                 1   37731.0      1
3                 2   43525.0      2
4                 2   39891.0      2
5                 2   56642.0      2
6                 3   60150.0      3
7                 3   54445.0      3
8                 3   64445.0      3
9                 3   57189.0      3
10                3   63218.0      3
11                4   55794.0      4
12                4   56957.0      4
13                4   57081.0      4
14                4   61111.0      4
15                4   67938.0      4
16                5   66029.0      5
17                5   83088.0      5
18                5   81363.0      5
19                6   93940.0      6
20                6   91738.0      6
21                7   98273.0      7
22                7  101302.0      7
23                8  113812.0      8
24                8  109431.0      8
25                9  105582.0      9
26                9  116969.0      9
27                9  112635.0      9
28               10  122391.0     10
29               10  121872.0     10

In [13]:
df.head()

   YearsExperience   Salary  years
0                1  39343.0      1
1                1  46205.0      1
2                1  37731.0      1
3                2  43525.0      2
4                2  39891.0      2

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     int64
 1   Salary           30 non-null     float64
 2   years            30 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 852.0 bytes

In [15]:
df.drop('YearsExperience', axis=1, inplace=True)  # axis 1 for columns, 0 for rows

In [16]:
df.head()

    Salary  years
0  39343.0      1
1  46205.0      1
2  37731.0      1
3  43525.0      2
4  39891.0      2

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Salary  30 non-null     float64
 1   years   30 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 612.0 bytes

In [19]:
print('Number of Rows and Columns:', df.shape)

Number of Rows and Columns: (30, 2)

In [20]:
df['years'].describe()  #stastical info of the given column

count    30.000000
mean      4.933333
std       2.790789
min       1.000000
25%       3.000000
50%       4.000000
75%       7.000000
max      10.000000
Name: years, dtype: float64

In [21]:
df.describe()

              Salary      years
count      30.000000  30.000000
mean    76003.000000   4.933333
std     27414.429785   2.790789
min     37731.000000   1.000000
25%     56720.750000   3.000000
50%     65237.000000   4.000000
75%    100544.750000   7.000000
max    122391.000000  10.000000

In [23]:
df

      Salary  years
0    39343.0      1
1    46205.0      1
2    37731.0      1
3    43525.0      2
4    39891.0      2
5    56642.0      2
6    60150.0      3
7    54445.0      3
8    64445.0      3
9    57189.0      3
10   63218.0      3
11   55794.0      4
12   56957.0      4
13   57081.0      4
14   61111.0      4
15   67938.0      4
16   66029.0      5
17   83088.0      5
18   81363.0      5
19   93940.0      6
20   91738.0      6
21   98273.0      7
22  101302.0      7
23  113812.0      8
24  109431.0      8
25  105582.0      9
26  116969.0      9
27  112635.0      9
28  122391.0     10
29  121872.0     10

In [24]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (2.4.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (1.17.1)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 1.0 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/8.1 MB 1.0 MB/s eta 0:00:08
   ----- ---------------------------------- 1.0/8.1 MB 1.0 MB/s eta 0:00:07
   ------ --------------------------------- 1.3/8.1 MB 1.0 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.1 MB 1.0 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.1 MB 1.0 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.1 MB 1.0 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.1 MB 1.0 MB/s eta 0:00:07
   --------- ------------------------------ 1.8/8.1 MB 824.6 kB/s eta 0:00:08
   --------- ------------------------------ 1.8/8.1 MB 824.6 kB/s eta 0:00:08
   ---------- ----------------------------- 2.1/8.1 MB 721.5 kB/s eta 0:00:09
   ---------- ----------------------------- 2.1/8.1 MB 721.5 kB/s eta 0:00:09
   ---------- ----------------------------- 2.1/8.1 MB 721.5 kB/s eta 0:00:09
   ----------- ---------------------------- 2.4/8.1 MB 672.9 kB/s eta 0:00:09
   ----------- ---------------------------- 2.4/8.1 MB 672.9 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.1 MB 662.2 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.1 MB 662.2 kB/s eta 0:00:09
   -------------- ------------------------- 2.9/8.1 MB 659.7 kB/s eta 0:00:08
   -------------- ------------------------- 2.9/8.1 MB 659.7 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.1 MB 675.9 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.1 MB 688.9 kB/s eta 0:00:07
   ---------------- ----------------------- 3.4/8.1 MB 688.9 kB/s eta 0:00:07
   ------------------ --------------------- 3.7/8.1 MB 698.3 kB/s eta 0:00:07
   ------------------- -------------------- 3.9/8.1 MB 707.5 kB/s eta 0:00:06
   -------------------- ------------------- 4.2/8.1 MB 716.5 kB/s eta 0:00:06
   -------------------- ------------------- 4.2/8.1 MB 716.5 kB/s eta 0:00:06
   ---------------------- ----------------- 4.5/8.1 MB 728.4 kB/s eta 0:00:05
   ----------------------- ---------------- 4.7/8.1 MB 745.7 kB/s eta 0:00:05
   ------------------------ --------------- 5.0/8.1 MB 759.8 kB/s eta 0:00:05
   ------------------------- -------------- 5.2/8.1 MB 772.5 kB/s eta 0:00:04
   --------------------------- ------------ 5.5/8.1 MB 779.4 kB/s eta 0:00:04
   --------------------------- ------------ 5.5/8.1 MB 779.4 kB/s eta 0:00:04
   ---------------------------- ----------- 5.8/8.1 MB 776.8 kB/s eta 0:00:03
   ----------------------------- ---------- 6.0/8.1 MB 781.1 kB/s eta 0:00:03
   ----------------------------- ---------- 6.0/8.1 MB 781.1 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.1 MB 775.9 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.1 MB 775.9 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.1 MB 783.1 kB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 784.0 kB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.1 MB 795.2 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 799.4 kB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 799.4 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 806.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 814.7 kB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 817.6 kB/s  0:00:09
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn

   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   ---------------------------------------- 3/3 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x=df.drop('Salary',axis=1)   #independent variables
y=df['Salary']  # target/ dependent variable

In [28]:
pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.6-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from statsmodels) (2.4.0)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from statsmodels) (1.17.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from statsmodels) (2.3.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from statsmodels) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.6-cp314-cp314-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 946.0 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.6 MB 992.5 kB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.6 MB 1.0 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.6 MB 1.0 MB/s eta 0:00:09
   ----- ---------------------------------- 1.3/9.6 MB 936.9 kB/s eta 0:00:09
   ------ --------------------------------- 1.6/9.6 MB 932.1 kB/s eta 0:00:09
   ------ --------------------------------- 1.6/9.6 MB 932.1 kB/s eta 0:00:09
   ------- -------------------------------- 1.8/9.6 MB 894.3 kB/s eta 0:00:09
   -------- ------------------------------- 2.1/9.6 MB 922.5 kB/s eta 0:00:09
   --------- ------------------------------ 2.4/9.6 MB 940.8 kB/s eta 0:00:08
   ---------- ----------------------------- 2.6/9.6 MB 966.4 kB/s eta 0:00:08
   ---------- ----------------------------- 2.6/9.6 MB 966.4 kB/s eta 0:00:08
   ------------ --------------------------- 2.9/9.6 MB 943.3 kB/s eta 0:00:08
   ------------- -------------------------- 3.1/9.6 MB 952.5 kB/s eta 0:00:07
   -------------- ------------------------- 3.4/9.6 MB 971.6 kB/s eta 0:00:07
   --------------- ------------------------ 3.7/9.6 MB 983.4 kB/s eta 0:00:07
   ---------------- ----------------------- 3.9/9.6 MB 973.2 kB/s eta 0:00:06
   ----------------- ---------------------- 4.2/9.6 MB 985.1 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.6 MB 983.1 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.6 MB 983.1 kB/s eta 0:00:06
   ------------------- -------------------- 4.7/9.6 MB 949.3 kB/s eta 0:00:06
   ------------------- -------------------- 4.7/9.6 MB 949.3 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.6 MB 939.2 kB/s eta 0:00:05
   -------------------- ------------------- 5.0/9.6 MB 939.2 kB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.6 MB 893.1 kB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.6 MB 893.1 kB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.6 MB 893.1 kB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.6 MB 861.2 kB/s eta 0:00:05
   ------------------------ --------------- 5.8/9.6 MB 854.2 kB/s eta 0:00:05
   ------------------------ --------------- 5.8/9.6 MB 854.2 kB/s eta 0:00:05
   ------------------------- -------------- 6.0/9.6 MB 851.7 kB/s eta 0:00:05
   -------------------------- ------------- 6.3/9.6 MB 862.0 kB/s eta 0:00:04
   --------------------------- ------------ 6.6/9.6 MB 869.7 kB/s eta 0:00:04
   ---------------------------- ----------- 6.8/9.6 MB 865.8 kB/s eta 0:00:04
   ---------------------------- ----------- 6.8/9.6 MB 865.8 kB/s eta 0:00:04
   ----------------------------- ---------- 7.1/9.6 MB 866.5 kB/s eta 0:00:03
   ------------------------------ --------- 7.3/9.6 MB 866.7 kB/s eta 0:00:03
   ------------------------------- -------- 7.6/9.6 MB 869.4 kB/s eta 0:00:03
   ------------------------------- -------- 7.6/9.6 MB 869.4 kB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.6 MB 875.0 kB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.6 MB 871.4 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.6 MB 875.8 kB/s eta 0:00:02
   ------------------------------------ --- 8.7/9.6 MB 883.0 kB/s eta 0:00:02
   ------------------------------------ --- 8.7/9.6 MB 883.0 kB/s eta 0:00:02
   ------------------------------------- -- 8.9/9.6 MB 877.7 kB/s eta 0:00:01
   ------------------------------------- -- 8.9/9.6 MB 877.7 kB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 873.7 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 872.8 kB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 867.6 kB/s  0:00:11
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Installing collected packages: patsy, statsmodels

   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   ---------------------------------------- 2/2 [statsmodels]

Successfully installed patsy-1.0.2 statsmodels-0.14.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import statsmodels.api as sm

In [30]:
x_with_constant = sm.add_constant(x)
x_with_constant

    const  years
0     1.0      1
1     1.0      1
2     1.0      1
3     1.0      2
4     1.0      2
5     1.0      2
6     1.0      3
7     1.0      3
8     1.0      3
9     1.0      3
10    1.0      3
11    1.0      4
12    1.0      4
13    1.0      4
14    1.0      4
15    1.0      4
16    1.0      5
17    1.0      5
18    1.0      5
19    1.0      6
20    1.0      6
21    1.0      7
22    1.0      7
23    1.0      8
24    1.0      8
25    1.0      9
26    1.0      9
27    1.0      9
28    1.0     10
29    1.0     10

In [31]:
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x_with_constant, y, test_size=0.3, random_state=30)

In [35]:
x_test.head()

    const  years
15    1.0      4
28    1.0     10
26    1.0      9
10    1.0      3
24    1.0      8

In [37]:
x_train.index

Index([4, 11, 22, 18, 19, 1, 16, 7, 9, 3, 14, 17, 21, 2, 23, 12, 20, 27, 13,
       29, 5],
      dtype='int64')

In [38]:
import statsmodels.api as sm

In [40]:
model=sm.OLS(y_train,x_train).fit()    # statsmodel stastical model-- OLS (Ordinary Least Square)
model.summary()                        # sklearn- linear regression      # r squared value should be minimum

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.931
Model:                            OLS   Adj. R-squared:                  0.927
Method:                 Least Squares   F-statistic:                     256.3
Date:                Mon, 23 Mar 2026   Prob (F-statistic):           1.74e-12
Time:                        19:46:23   Log-Likelihood:                -214.92
No. Observations:                  21   AIC:                             433.8
Df Residuals:                      19   BIC:                             435.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.624e+04   3298.359      7.954      0.000    1.93e+04    3.31e+04
years       9996.7047    624.394     16.010      0.000    8689.833    1.13e+04
==============================================================================
Omnibus:                        4.673   Durbin-Watson:                   1.925
Prob(Omnibus):                  0.097   Jarque-Bera (JB):                1.531
Skew:                          -0.077   Prob(JB):                        0.465
Kurtosis:                       1.686   Cond. No.                         11.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
pred_train=

In [48]:
from sklearn.metrics import mean_squared_error

In [41]:
from sklearn.linear_model import LinearRegression

In [49]:
import numpy as np

In [55]:
train_rmse=np.sqrt(mean_squared_error(y_train,pred_train))
test_rmse=np.sqrt(mean_squared_error(ytest,pred_test))
print(f'Train RMSE:{train_rmse}')
print(f'Test RMSE:{test_rmse}')

NameError: name 'pred_train' is not defined

In [46]:
model_1=LinearRegression()
model_1.fit(x_train,y_train)

LinearRegression()

In [51]:
pred_train_1=model_1.predict(x_train)
pred_test_1=model_1.predict(x_test)

In [52]:
pred_train_1

array([ 46228.93042191,  66222.33974833,  96212.45373797,  76219.04441155,
        86215.74907476,  36232.2257587 ,  76219.04441155,  56225.63508512,
        56225.63508512,  46228.93042191,  66222.33974833,  76219.04441155,
        96212.45373797,  36232.2257587 , 106209.15840118,  66222.33974833,
        86215.74907476, 116205.8630644 ,  66222.33974833, 126202.56772761,
        46228.93042191])

In [53]:
pred_test_1

array([ 66222.33974833, 126202.56772761, 116205.8630644 ,  56225.63508512,
       106209.15840118,  36232.2257587 ,  56225.63508512,  56225.63508512,
       116205.8630644 ])