In [2]:
# A data frame is a two dimensional,size mutable ,and heter0geneous tabular data structure with labeled axes(rows and colums). It is similar to a spreadsheet or SQL table,or a dictionary of series objects

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\shash\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\shash\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shash\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shash\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shash\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\shash\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd 

data = {
    'Name': ['Aman', 'bob', 'Charlie', 'sura'],
    'Age': [25,34,45,17],
    'City': ['Pune', 'Mumbai', 'leh', 'Kol']
}

data

{'Name': ['Aman', 'bob', 'Charlie', 'sura'],
 'Age': [25, 34, 45, 17],
 'City': ['Pune', 'Mumbai', 'leh', 'Kol']}

In [5]:
df = pd.DataFrame(data)
df

      Name  Age    City
0     Aman   25    Pune
1      bob   34  Mumbai
2  Charlie   45     leh
3     sura   17     Kol

In [6]:
print('this  is the dataframe',df)

this  is the dataframe       Name  Age    City
0     Aman   25    Pune
1      bob   34  Mumbai
2  Charlie   45     leh
3     sura   17     Kol

In [7]:

data = [
    {'Name': 'Aman', 'Age': '25', 'City': 'Pune', 'Gender': 'Male'},
    {'Name': 'Bob', 'Age': '25', 'City': 'Kochi'},
    {'Name': 'Chandu', 'Age': '35', 'City': 'Chennai'}
]

df = pd.DataFrame(data)
df

     Name Age     City Gender
0    Aman  25     Pune   Male
1     Bob  25    Kochi    NaN
2  Chandu  35  Chennai    NaN

In [8]:
#1 view data
print(df)
print(df.head()) #first 5 rows of the dataset
print(df.tail())  # last 5 rows

     Name Age     City Gender
0    Aman  25     Pune   Male
1     Bob  25    Kochi    NaN
2  Chandu  35  Chennai    NaN
     Name Age     City Gender
0    Aman  25     Pune   Male
1     Bob  25    Kochi    NaN
2  Chandu  35  Chennai    NaN
     Name Age     City Gender
0    Aman  25     Pune   Male
1     Bob  25    Kochi    NaN
2  Chandu  35  Chennai    NaN

In [9]:
#2 structure & info
print(df.shape)   # total number of rows and colums

(3, 4)

In [10]:
print(df.columns)

Index(['Name', 'Age', 'City', 'Gender'], dtype='object')

In [11]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      object
 2   City    3 non-null      object
 3   Gender  1 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes
None

In [12]:
# 3. check missing values
print(df.isna())

    Name    Age   City  Gender
0  False  False  False   False
1  False  False  False    True
2  False  False  False    True

In [13]:
print(df.isna().sum())

Name      0
Age       0
City      0
Gender    2
dtype: int64

In [14]:
# 4 FILL MISSING VALUES
df['Name']=df['Name'].fillna('Unknown')

In [15]:
df['Gender']=df['Gender'].fillna('Not Specified')

In [16]:
df.isna().sum()

Name      0
Age       0
City      0
Gender    0
dtype: int64

In [17]:
print(df.isna())

    Name    Age   City  Gender
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False

In [18]:
#5 select colums
print(df['Name'])

0      Aman
1       Bob
2    Chandu
Name: Name, dtype: object

In [19]:
#6 select rows
print(df.iloc[0]) # 0 means first row
print(df.loc[1])
print(df.loc[0:2])

Name      Aman
Age         25
City      Pune
Gender    Male
Name: 0, dtype: object
Name                Bob
Age                  25
City              Kochi
Gender    Not Specified
Name: 1, dtype: object
     Name Age     City         Gender
0    Aman  25     Pune           Male
1     Bob  25    Kochi  Not Specified
2  Chandu  35  Chennai  Not Specified

In [20]:
# 7 filter data 
df["Age"] = df["Age"].astype(int)
print(df[df["Age"] > 25])

     Name  Age     City         Gender
2  Chandu   35  Chennai  Not Specified

In [21]:
print(df[(df['City'] == "pune") | (df["Age"] >= 30)])

     Name  Age     City         Gender
2  Chandu   35  Chennai  Not Specified

In [22]:
#8. add new colum
import numpy as np

df["Age_Group"] = np.where(df["Age"] < 30, "Young", "Adult")
print(df)

     Name  Age     City         Gender Age_Group
0    Aman   25     Pune           Male     Young
1     Bob   25    Kochi  Not Specified     Young
2  Chandu   35  Chennai  Not Specified     Adult

In [23]:
#9 rename column
df.rename(columns={"Gender": "gender"}, inplace=True)
print(df.columns)

Index(['Name', 'Age', 'City', 'gender', 'Age_Group'], dtype='object')

In [24]:
#10. sort data 
print(df.sort_values(by="Age", ascending=False)) #default is ascending order

     Name  Age     City         gender Age_Group
2  Chandu   35  Chennai  Not Specified     Adult
0    Aman   25     Pune           Male     Young
1     Bob   25    Kochi  Not Specified     Young

In [25]:
#11 unique & value counts
print(df["City"].unique())
print(df["gender"].value_counts())

['Pune' 'Kochi' 'Chennai']
gender
Not Specified    2
Male             1
Name: count, dtype: int64

In [26]:
print(df["gender"].value_counts())

gender
Not Specified    2
Male             1
Name: count, dtype: int64

In [27]:
# 12 drop column & row
print(df.drop(columns=["Age_Group"]))

     Name  Age     City         gender
0    Aman   25     Pune           Male
1     Bob   25    Kochi  Not Specified
2  Chandu   35  Chennai  Not Specified

In [28]:
print(df.drop(index=0))

     Name  Age     City         gender Age_Group
1     Bob   25    Kochi  Not Specified     Young
2  Chandu   35  Chennai  Not Specified     Adult

In [29]:
#13 index operation
print(df.set_index("Name"))

        Age     City         gender Age_Group
Name
Aman     25     Pune           Male     Young
Bob      25    Kochi  Not Specified     Young
Chandu   35  Chennai  Not Specified     Adult

In [30]:
print(df.reset_index(drop=True))

     Name  Age     City         gender Age_Group
0    Aman   25     Pune           Male     Young
1     Bob   25    Kochi  Not Specified     Young
2  Chandu   35  Chennai  Not Specified     Adult

In [31]:
#14 export data
df.to_csv("people_data.csv", index=False)
print("All operation completed successfully")

All operation completed successfully

In [32]:
import pandas as pd

data = [
    {'Name': 'Aman', 'Age': 24, 'City': 'Pune', 'gender': 'Male'},
    {'Name': 'Bob', 'Age': 25, 'City': 'Kochi'},
    {'Name': 'Chandu', 'Age': 35, 'City': 'Chennai'}
]

df = pd.DataFrame(data)

df

     Name  Age     City gender
0    Aman   24     Pune   Male
1     Bob   25    Kochi    NaN
2  Chandu   35  Chennai    NaN

In [33]:
#  STEP 2 data cleaning adv
df["Name"] =  df["Name"].fillna("Unknown")
df["gender"] = df["gender"].fillna("Not Specified")

df["Name"] = df["Name"].str.lower()
df["City"] = df["City"].str.upper()
df["gender"] = df["gender"].str.capitalize()
display(df)

     Name  Age     City         gender
0    aman   24     PUNE           Male
1     bob   25    KOCHI  Not specified
2  chandu   35  CHENNAI  Not specified

In [34]:
# step 3 conditional colum (lamdba)
df["Age_Group"] = df["Age"].apply(
    lambda x: "Young" if x < 30 else "Mid" if x < 35 else "Senior"
)

print(df)

     Name  Age     City         gender Age_Group
0    aman   24     PUNE           Male     Young
1     bob   25    KOCHI  Not specified     Young
2  chandu   35  CHENNAI  Not specified    Senior

In [35]:
#step 4 map vs apply
age_map = {25: "Junior", 30:"Associate", 35: "Senior"}
df["Experincde_Level"] = df["Age"].map(age_map)
display(df)

     Name  Age     City         gender Age_Group Experincde_Level
0    aman   24     PUNE           Male     Young              NaN
1     bob   25    KOCHI  Not specified     Young           Junior
2  chandu   35  CHENNAI  Not specified    Senior           Senior

In [36]:
#STEP 5. vectorize multiple cindition
conditions = [
    (df["Age"] < 30),
    (df["Age"].between (30,34)),
    (df["Age"] >= 35)
]
choices = ["Low", "Medium", "High"]
df["Risk_Level"] = np.select(conditions, choices, default="Unknown")
display(df)

     Name  Age     City         gender Age_Group Experincde_Level Risk_Level
0    aman   24     PUNE           Male     Young              NaN        Low
1     bob   25    KOCHI  Not specified     Young           Junior        Low
2  chandu   35  CHENNAI  Not specified    Senior           Senior       High

In [37]:
# STEP6 query(SQL like filtering) filtering the data frame to create filtered_df
filtered_df = df.query("Age >= 30 and City != 'Pune'")
display(filtered_df)

     Name  Age     City         gender Age_Group Experincde_Level Risk_Level
2  chandu   35  CHENNAI  Not specified    Senior           Senior       High

In [38]:
#step 7 assign (chain operation) adding 'Age_Squared' and 'Name_length' colums using chaianed assign operation

df = (
    df.assign(
        age_Squared = lambda x: x["Age"] ** 2,
        Name_Length = lambda x: x["Name"].str.len()
    )
)
display(df)

,Name,Age,City,gender,Age_Group,Experincde_Level,Risk_Level,age_Squared,Name_Length
0,aman,24,PUNE,Male,Young,NaN,Low,576,4
1,bob,25,KOCHI,Not specified,Young,Junior,Low,625,3
2,chandu,35,CHENNAI,Not specified,Senior,Senior,High,1225,6

In [39]:
#step 8  Apply Across Rows (Axis=1)
#Creating aPrifile column by applying a function row Wise
df["Profile"] = df.apply(
    lambda row: f"{row['Name']} ({row['City']}) - {row['Age']} yrs old",
    axis=1
)

display(df)

,Name,Age,City,gender,Age_Group,Experincde_Level,Risk_Level,age_Squared,Name_Length,Profile
0,aman,24,PUNE,Male,Young,NaN,Low,576,4,aman (PUNE) - 24 yrs old
1,bob,25,KOCHI,Not specified,Young,Junior,Low,625,3,bob (KOCHI) - 25 yrs old
2,chandu,35,CHENNAI,Not specified,Senior,Senior,High,1225,6,chandu (CHENNAI) - 35 yrs old

In [40]:
#step=9 String advanced operations
df["City_Code"] = df["City"].str[:3]
df["Name_Initial"] = df["Name"].str[0]
display(df)

,Name,Age,City,gender,Age_Group,Experincde_Level,Risk_Level,age_Squared,Name_Length,Profile,City_Code,Name_Initial
0,aman,24,PUNE,Male,Young,NaN,Low,576,4,aman (PUNE) - 24 yrs old,PUN,a
1,bob,25,KOCHI,Not specified,Young,Junior,Low,625,3,bob (KOCHI) - 25 yrs old,KOC,b
2,chandu,35,CHENNAI,Not specified,Senior,Senior,High,1225,6,chandu (CHENNAI) - 35 yrs old,CHE,c

In [46]:
#Step=10 Sort + Rank
df["Age_Rank"] = df["Age"].rank(ascending=False)
df = df.sort_values("Age_Rank")
print(df)

     Name  Age     City         gender Age_Group Experincde_Level Risk_Level  \
2  chandu   35  CHENNAI  Not specified    Senior           Senior       High
1     bob   25    KOCHI  Not specified     Young           Junior        Low
0    aman   24     PUNE           Male     Young              NaN        Low

   age_Squared  Name_Length                        Profile City_Code  \
2         1225            6  chandu (CHENNAI) - 35 yrs old       CHE
1          625            3       bob (KOCHI) - 25 yrs old       KOC
0          576            4       aman (PUNE) - 24 yrs old       PUN

  Name_Initial  Age_Rolling_Mean  Is_Duplicate_Name  Age_Rank
2            c              30.0              False       1.0
1            b              24.5              False       2.0
0            a               NaN              False       3.0

In [47]:
#Step=11 Window Function(calculating the 'Age_Rolling_Mean'using a rolling window)
df['Age_Rolling_Mean'] = df['Age'].rolling(window=2).mean()
print(df)

     Name  Age     City         gender Age_Group Experincde_Level Risk_Level  \
2  chandu   35  CHENNAI  Not specified    Senior           Senior       High
1     bob   25    KOCHI  Not specified     Young           Junior        Low
0    aman   24     PUNE           Male     Young              NaN        Low

   age_Squared  Name_Length                        Profile City_Code  \
2         1225            6  chandu (CHENNAI) - 35 yrs old       CHE
1          625            3       bob (KOCHI) - 25 yrs old       KOC
0          576            4       aman (PUNE) - 24 yrs old       PUN

  Name_Initial  Age_Rolling_Mean  Is_Duplicate_Name  Age_Rank
2            c               NaN              False       1.0
1            b              30.0              False       2.0
0            a              24.5              False       3.0

In [48]:
#step=12 Dupliucate checking (adv) identifying duplicate names in the dataframe
df["Is_Duplicate_Name"] = df.duplicated(subset=["Name"])
print(df)

     Name  Age     City         gender Age_Group Experincde_Level Risk_Level  \
2  chandu   35  CHENNAI  Not specified    Senior           Senior       High
1     bob   25    KOCHI  Not specified     Young           Junior        Low
0    aman   24     PUNE           Male     Young              NaN        Low

   age_Squared  Name_Length                        Profile City_Code  \
2         1225            6  chandu (CHENNAI) - 35 yrs old       CHE
1          625            3       bob (KOCHI) - 25 yrs old       KOC
0          576            4       aman (PUNE) - 24 yrs old       PUN

  Name_Initial  Age_Rolling_Mean  Is_Duplicate_Name  Age_Rank
2            c               NaN              False       1.0
1            b              30.0              False       2.0
0            a              24.5              False       3.0

In [49]:
#Step=13 Memory & Performance
df["Age"] = df["Age"].astype("int16")
print(df.dtypes)

Name                  object
Age                    int16
City                  object
gender                object
Age_Group             object
Experincde_Level      object
Risk_Level            object
age_Squared            int64
Name_Length            int64
Profile               object
City_Code             object
Name_Initial          object
Age_Rolling_Mean     float64
Is_Duplicate_Name       bool
Age_Rank             float64
dtype: object

In [51]:
#Step=14 Pipe (Function Style)
def normalize_age(frame):
    frame["Age_Normalized"] = (frame["Age"] - frame["Age"].min()) / (
        frame["Age"].max() - frame["Age"].min()
    )
    return frame

df = df.pipe(normalize_age)

print(df)

     Name  Age     City         gender Age_Group Experincde_Level Risk_Level  \
2  chandu   35  CHENNAI  Not specified    Senior           Senior       High
1     bob   25    KOCHI  Not specified     Young           Junior        Low
0    aman   24     PUNE           Male     Young              NaN        Low

   age_Squared  Name_Length                        Profile City_Code  \
2         1225            6  chandu (CHENNAI) - 35 yrs old       CHE
1          625            3       bob (KOCHI) - 25 yrs old       KOC
0          576            4       aman (PUNE) - 24 yrs old       PUN

  Name_Initial  Age_Rolling_Mean  Is_Duplicate_Name  Age_Rank  Age_Normalized
2            c               NaN              False       1.0        1.000000
1            b              30.0              False       2.0        0.090909
0            a              24.5              False       3.0        0.000000

In [53]:
#Step=15 Final Output summary
print("/nFinal Transformed DataFrame:")
print(df)
print("/nFiltered DataFrame (from earlier query):")
print(filtered_df)
print("/nData Types of Final DataFrame:")
print(df.dtypes)

/nFinal Transformed DataFrame:
     Name  Age     City         gender Age_Group Experincde_Level Risk_Level  \
2  chandu   35  CHENNAI  Not specified    Senior           Senior       High
1     bob   25    KOCHI  Not specified     Young           Junior        Low
0    aman   24     PUNE           Male     Young              NaN        Low

   age_Squared  Name_Length                        Profile City_Code  \
2         1225            6  chandu (CHENNAI) - 35 yrs old       CHE
1          625            3       bob (KOCHI) - 25 yrs old       KOC
0          576            4       aman (PUNE) - 24 yrs old       PUN

  Name_Initial  Age_Rolling_Mean  Is_Duplicate_Name  Age_Rank  Age_Normalized
2            c               NaN              False       1.0        1.000000
1            b              30.0              False       2.0        0.090909
0            a              24.5              False       3.0        0.000000
/nFiltered DataFrame (from earlier query):
     Name  Age     City         gender Age_Group Experincde_Level Risk_Level
2  chandu   35  CHENNAI  Not specified    Senior           Senior       High
/nData Types of Final DataFrame:
Name                  object
Age                    int16
City                  object
gender                object
Age_Group             object
Experincde_Level      object
Risk_Level            object
age_Squared            int64
Name_Length            int64
Profile               object
City_Code             object
Name_Initial          object
Age_Rolling_Mean     float64
Is_Duplicate_Name       bool
Age_Rank             float64
Age_Normalized       float64
dtype: object